{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 71,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Exception Found in get_data method!\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-71-2469212db060>\", line 31, in get_data\n",
      "    soup = parse_page(url)\n",
      "  File \"<ipython-input-71-2469212db060>\", line 12, in parse_page\n",
      "    review_html = requests.get(url, headers = header).text\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/api.py\", line 70, in get\n",
      "    return request('get', url, params=params, **kwargs)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/api.py\", line 56, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/sessions.py\", line 474, in request\n",
      "    prep = self.prepare_request(req)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/sessions.py\", line 407, in prepare_request\n",
      "    hooks=merge_hooks(request.hooks, self.hooks),\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/models.py\", line 302, in prepare\n",
      "    self.prepare_url(url, params)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/models.py\", line 382, in prepare_url\n",
      "    raise MissingSchema(error)\n",
      "requests.exceptions.MissingSchema: Invalid URL '/shop/h/deals': No schema supplied. Perhaps you meant http:///shop/h/deals?\n",
      "ERROR:root:Exception Found in get_data method!\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-71-2469212db060>\", line 31, in get_data\n",
      "    soup = parse_page(url)\n",
      "  File \"<ipython-input-71-2469212db060>\", line 12, in parse_page\n",
      "    review_html = requests.get(url, headers = header).text\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/api.py\", line 70, in get\n",
      "    return request('get', url, params=params, **kwargs)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/api.py\", line 56, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/sessions.py\", line 474, in request\n",
      "    prep = self.prepare_request(req)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/sessions.py\", line 407, in prepare_request\n",
      "    hooks=merge_hooks(request.hooks, self.hooks),\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/models.py\", line 302, in prepare\n",
      "    self.prepare_url(url, params)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/models.py\", line 382, in prepare_url\n",
      "    raise MissingSchema(error)\n",
      "requests.exceptions.MissingSchema: Invalid URL '/shop/h/gift-cards': No schema supplied. Perhaps you meant http:///shop/h/gift-cards?\n",
      "ERROR:root:Exception Found in get_data method!\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-71-2469212db060>\", line 31, in get_data\n",
      "    soup = parse_page(url)\n",
      "  File \"<ipython-input-71-2469212db060>\", line 12, in parse_page\n",
      "    review_html = requests.get(url, headers = header).text\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/api.py\", line 70, in get\n",
      "    return request('get', url, params=params, **kwargs)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/api.py\", line 56, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/sessions.py\", line 474, in request\n",
      "    prep = self.prepare_request(req)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/sessions.py\", line 407, in prepare_request\n",
      "    hooks=merge_hooks(request.hooks, self.hooks),\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/models.py\", line 302, in prepare\n",
      "    self.prepare_url(url, params)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/models.py\", line 382, in prepare_url\n",
      "    raise MissingSchema(error)\n",
      "requests.exceptions.MissingSchema: Invalid URL '/shop/h/accessories': No schema supplied. Perhaps you meant http:///shop/h/accessories?\n",
      "ERROR:root:Exception Found in get_data method!\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-71-2469212db060>\", line 31, in get_data\n",
      "    soup = parse_page(url)\n",
      "  File \"<ipython-input-71-2469212db060>\", line 12, in parse_page\n",
      "    review_html = requests.get(url, headers = header).text\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/api.py\", line 70, in get\n",
      "    return request('get', url, params=params, **kwargs)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/api.py\", line 56, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/sessions.py\", line 474, in request\n",
      "    prep = self.prepare_request(req)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/sessions.py\", line 407, in prepare_request\n",
      "    hooks=merge_hooks(request.hooks, self.hooks),\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/models.py\", line 302, in prepare\n",
      "    self.prepare_url(url, params)\n",
      "  File \"/home/sahib/Apps/Anaconda/lib/python3.6/site-packages/requests/models.py\", line 382, in prepare_url\n",
      "    raise MissingSchema(error)\n",
      "requests.exceptions.MissingSchema: Invalid URL '/shop/h/footwears': No schema supplied. Perhaps you meant http:///shop/h/footwears?\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "from docx import Document\n",
    "import logging\n",
    "import time\n",
    "\n",
    "document = Document()\n",
    "header = {'user-agent': 'curl/7.0'}\n",
    "required_urls = []\n",
    "\n",
    "def parse_page(url):\n",
    "    review_html = requests.get(url, headers = header).text\n",
    "    soup = BeautifulSoup(review_html, 'lxml')\n",
    "    return soup\n",
    "\n",
    "def get_urls():\n",
    "    url = \"https://paytm.com/\"\n",
    "    soup = parse_page(url)\n",
    "    div_classes = ['_2kcr','_17WC']\n",
    "\n",
    "    for div_class in div_classes:\n",
    "        for data in soup.find_all('div', {'class': div_class}):\n",
    "            for a in data.find_all('a'):\n",
    "                required_urls.append(a.get('href'))\n",
    "\n",
    "def get_data():\n",
    "    div_sub_classes = ['nA7q', 'wk_w','_22U6']\n",
    "\n",
    "    for url in required_urls:\n",
    "        try:\n",
    "            soup = parse_page(url)\n",
    "            description_tag = soup.find(attrs={\"name\":\"og:description\"})\n",
    "            description = description_tag[\"content\"] if description_tag else \"No Meta Description given\"\n",
    "            title_tag = soup.find(\"meta\", property=\"og:title\")            \n",
    "            title = title_tag[\"content\"] if title_tag else \"No Meta Title given\"\n",
    "            for div_sub_class in div_sub_classes:\n",
    "                for data in soup.find_all('div', {'class': div_sub_class}):\n",
    "                    document.add_heading(url+ \"\\n\")\n",
    "                    document.add_paragraph(\"Title:\\n \"+ title)\n",
    "                    document.add_paragraph(\"Description: \\n \"+ description)\n",
    "                    document.add_paragraph(\"Data: \\n \"+ data.text)\n",
    "        # Wait for 1 second\n",
    "            time.sleep(1)\n",
    "        except Exception as ex:            \n",
    "            logging.exception(\"Exception Found in get_data method!\")\n",
    "\n",
    "def save_data():\n",
    "    document.save('Paytm_Scraped.docx')\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    get_urls()\n",
    "    get_data()\n",
    "    save_data()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
